name: Ruff Checks

on: [push, pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x' # Use a version compatible with your project
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          # If you have other dependencies needed for ruff to run (e.g., plugins)
          # install them here, for example:
          # pip install -r requirements-dev.txt
      - name: Run ruff linter
        run: ruff check .
      - name: Run ruff formatter
        run: ruff format . --check # --check flag makes it fail if files need formatting
